/**
 * Skill Catalog (HTML reference)
 *
 * Renders `docs/skill-catalog.html` — a self-contained, theme-aware reference
 * for the bundled skill set, generated by `npm run build` from `skills/*.md`
 * frontmatter. It is the structured counterpart to the flat markdown table in
 * `docs/skills.md`.
 *
 * Why an HTML artifact and not another table: the page's **Enforcement** column
 * is load-bearing. `safety-guard` shipped for months describing a runtime gate,
 * a slash command, and a log writer while shipping none of them, because a
 * markdown row has nowhere to state what actually backs a skill. Here every
 * skill renders one of three badges, derived from the shipped file set — not
 * from prose — so a prose-only skill cannot present itself as a runtime gate:
 *
 *   hook    — a hook in `hooks/` enforces it at the tool boundary
 *   command — a `commands/<name>.md` slash command invokes it
 *   prose   — model-side discipline only; nothing blocks or fires automatically
 *
 * `hooks/` filenames do not match skill names one-to-one (goal-monitor is
 * enforced by `goal-drift-stop.mjs`), so the mapping is declared explicitly in
 * HOOK_BY_SKILL below. An unmapped skill degrades to `command` or `prose` —
 * never to `hook`. Fail-closed is the point: an unlisted skill under-claims.
 */
import type { SkillMeta, SkillTier } from "./skill-tiers.mjs";

/** Enforcement surface actually backing a skill. */
export type Enforcement = "hook" | "command" | "prose";

/** Skill plus the facts the catalog renders beyond name/tier/description. */
export interface CatalogSkill extends SkillMeta {
  enforcement: Enforcement;
  /** `hooks/<file>` that enforces this skill, when enforcement is "hook". */
  hookFile?: string;
  /** Law tag lifted from the description, e.g. "1", "3 + 4", "all 7". */
  law?: string;
}

/**
 * Skill -> enforcing hook filename. Explicit because hook filenames describe
 * the event they fire on, not the skill they serve. Adding a hook without
 * adding its row here makes the catalog under-claim, which is the safe
 * direction.
 */
export const HOOK_BY_SKILL: Readonly<Record<string, string>> = {
  gateguard: "gateguard.mjs",
  "goal-monitor": "goal-drift-stop.mjs",
  recall: "recall-briefing.mjs",
  superpowers: "companion-preference.mjs",
  "verification-loop": "typecheck-stop.mjs",
  "skill-distillation": "workflow-distill.mjs",
};

const TIER_LABEL: Record<SkillTier, string> = {
  core: "Core",
  featured: "Featured",
  "1": "Tier 1 — beginner",
  "2": "Tier 2 — expert",
  companion: "Always bundled",
  unknown: "Unclassified",
};

const TIER_ORDER: SkillTier[] = ["core", "featured", "1", "2", "companion", "unknown"];

const ENFORCEMENT_TITLE: Record<Enforcement, string> = {
  hook: "Enforced at the tool boundary by a hook — it fires whether or not the model cooperates.",
  command: "Invoked by a slash command. Runs when you ask for it.",
  prose: "Model-side discipline only. Nothing blocks and nothing fires automatically.",
};

/** Lift the Law tag out of a Law-tagged description. */
export function lawOf(description: string | undefined): string | undefined {
  if (!description) return undefined;
  if (/\ball\s+7\s+Laws\b/i.test(description)) return "all 7";
  if (/\bLaw\s+activator\b/i.test(description)) return "activator";
  const multi = description.match(/\bLaw\s*([1-7])\s*\+\s*([1-7])\b/i);
  if (multi) return `${multi[1]} + ${multi[2]}`;
  const single = description.match(/\bLaw\s*([1-7])\b/i);
  return single ? single[1] : undefined;
}

/** Resolve the enforcement surface for one skill from the shipped file set. */
export function enforcementOf(
  name: string,
  commandNames: ReadonlySet<string>,
): { enforcement: Enforcement; hookFile?: string } {
  const hookFile = HOOK_BY_SKILL[name];
  if (hookFile) return { enforcement: "hook", hookFile };
  if (commandNames.has(name)) return { enforcement: "command" };
  return { enforcement: "prose" };
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Strip the "Enforces Law N (…) of the 7 Laws…" preamble; keep what it does. */
export function summarize(description: string | undefined): string {
  if (!description) return "";
  return description
    .replace(/^Enforces\s+(all\s+7\s+Laws|Law\s*[1-7](\s*\+\s*[1-7])?)[^.]*\.\s*/i, "")
    .replace(/^Use this skill to\s*/i, "")
    .trim();
}

const STYLE = `
:root { color-scheme: light dark; --bg:#fbfbfa; --fg:#1a1a19; --muted:#6b6b66;
  --line:#e3e3df; --card:#fff; --hook:#0f6f4b; --hookbg:#e4f3ec;
  --cmd:#1b4f8a; --cmdbg:#e5eefa; --prose:#8a5a12; --prosebg:#faf0dc; }
@media (prefers-color-scheme: dark) { :root { --bg:#121211; --fg:#ececeb;
  --muted:#9a9a94; --line:#2c2c29; --card:#1b1b1a; --hook:#6fd3a8; --hookbg:#12332a;
  --cmd:#8fbdf0; --cmdbg:#132840; --prose:#e3b464; --prosebg:#3a2c12; } }
:root[data-theme="dark"] { --bg:#121211; --fg:#ececeb; --muted:#9a9a94; --line:#2c2c29;
  --card:#1b1b1a; --hook:#6fd3a8; --hookbg:#12332a; --cmd:#8fbdf0; --cmdbg:#132840;
  --prose:#e3b464; --prosebg:#3a2c12; }
:root[data-theme="light"] { --bg:#fbfbfa; --fg:#1a1a19; --muted:#6b6b66; --line:#e3e3df;
  --card:#fff; --hook:#0f6f4b; --hookbg:#e4f3ec; --cmd:#1b4f8a; --cmdbg:#e5eefa;
  --prose:#8a5a12; --prosebg:#faf0dc; }
body { margin:0; padding:2.5rem 1.25rem 4rem; background:var(--bg); color:var(--fg);
  font:16px/1.6 ui-sans-serif,-apple-system,"Segoe UI",Roboto,sans-serif; }
.wrap { max-width:70rem; margin:0 auto; }
h1 { font-size:1.75rem; margin:0 0 .35rem; letter-spacing:-.015em; }
.sub { color:var(--muted); margin:0 0 1.25rem; max-width:52rem; }
h2 { font-size:1rem; text-transform:uppercase; letter-spacing:.08em; color:var(--muted);
  margin:2.5rem 0 .75rem; font-weight:600; }
.legend { display:flex; flex-wrap:wrap; gap:1rem; margin:0 0 1rem; padding:0; list-style:none; }
.legend li { color:var(--muted); font-size:.85rem; }
.scroll { overflow-x:auto; border:1px solid var(--line); border-radius:.6rem; background:var(--card); }
table { border-collapse:collapse; width:100%; min-width:44rem; }
th, td { text-align:left; padding:.7rem .85rem; border-bottom:1px solid var(--line); vertical-align:top; }
th { font-size:.78rem; text-transform:uppercase; letter-spacing:.06em; color:var(--muted); font-weight:600; }
tr:last-child td { border-bottom:0; }
td.name { font-family:ui-monospace,SFMono-Regular,Menlo,monospace; font-size:.88rem; white-space:nowrap; }
td.law { color:var(--muted); white-space:nowrap; font-variant-numeric:tabular-nums; }
td.what { min-width:22rem; }
.badge { display:inline-block; padding:.12rem .5rem; border-radius:1rem; font-size:.75rem;
  font-weight:600; white-space:nowrap; }
.badge.hook { color:var(--hook); background:var(--hookbg); }
.badge.command { color:var(--cmd); background:var(--cmdbg); }
.badge.prose { color:var(--prose); background:var(--prosebg); }
.hookfile { display:block; margin-top:.25rem; font-family:ui-monospace,monospace;
  font-size:.72rem; color:var(--muted); }
footer { margin-top:3rem; color:var(--muted); font-size:.85rem; max-width:52rem; }
code { font-family:ui-monospace,monospace; font-size:.9em; }
`;

/**
 * Render the full catalog page. Pure — takes the resolved skill list and
 * returns the complete HTML document.
 */
export function renderSkillCatalogHtml(skills: readonly CatalogSkill[]): string {
  const counts: Record<Enforcement, number> = { hook: 0, command: 0, prose: 0 };
  for (const s of skills) counts[s.enforcement]++;

  const sections: string[] = [];
  for (const tier of TIER_ORDER) {
    const rows = skills.filter((s) => s.tier === tier);
    if (rows.length === 0) continue;
    const body = rows
      .map((s) => {
        const badge =
          `<span class="badge ${s.enforcement}" title="${escapeHtml(ENFORCEMENT_TITLE[s.enforcement])}">` +
          `${s.enforcement}</span>` +
          (s.hookFile ? `<span class="hookfile">hooks/${escapeHtml(s.hookFile)}</span>` : "");
        return (
          "        <tr>" +
          `<td class="name">${escapeHtml(s.name)}</td>` +
          `<td class="law">${escapeHtml(s.law ?? "—")}</td>` +
          `<td>${badge}</td>` +
          `<td class="what">${escapeHtml(summarize(s.description))}</td>` +
          "</tr>"
        );
      })
      .join("\n");
    sections.push(
      `    <h2>${escapeHtml(TIER_LABEL[tier])} (${rows.length})</h2>\n` +
        '    <div class="scroll">\n      <table>\n' +
        "        <thead><tr><th>Skill</th><th>Law</th><th>Enforcement</th><th>What it does</th></tr></thead>\n" +
        `        <tbody>\n${body}\n        </tbody>\n` +
        "      </table>\n    </div>",
    );
  }

  return [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '  <meta charset="utf-8">',
    '  <meta name="viewport" content="width=device-width,initial-scale=1">',
    `  <title>Skill catalog — continuous-improvement (${skills.length} skills)</title>`,
    "  <!-- GENERATED by npm run build from skills/*.md frontmatter. Do not edit by hand. -->",
    `  <style>${STYLE}  </style>`,
    "</head>",
    "<body>",
    '  <div class="wrap">',
    "    <h1>Skill catalog</h1>",
    `    <p class="sub">${skills.length} bundled skills, generated from <code>skills/*.md</code> frontmatter. ` +
      "The <strong>Enforcement</strong> column is the point of this page: it states what actually backs each skill, " +
      "derived from the shipped file set rather than from the skill's own prose. " +
      `Today ${counts.hook} are enforced by a hook, ${counts.command} by a slash command, and ${counts.prose} by model-side discipline alone.</p>`,
    '    <ul class="legend">',
    '      <li><span class="badge hook">hook</span> fires at the tool boundary; model cooperation not required</li>',
    '      <li><span class="badge command">command</span> runs when you invoke it</li>',
    '      <li><span class="badge prose">prose</span> model-side discipline only — nothing blocks</li>',
    "    </ul>",
    sections.join("\n"),
    '    <footer>A skill may only claim enforcement it ships. A <span class="badge prose">prose</span> skill that describes a runtime gate is a bug — that is what retired <code>safety-guard</code> on 2026-08-07. See <code>docs/plans/2026-08-07-six-rules-context-engineering.md</code>.</footer>',
    "  </div>",
    "</body>",
    "</html>",
    "",
  ].join("\n");
}
