import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { HOOK_BY_SKILL, enforcementOf, lawOf, renderSkillCatalogHtml, summarize, } from "../lib/skill-catalog.mjs";
const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
describe("skill-catalog — lawOf", () => {
    it("lifts a single Law tag", () => {
        assert.equal(lawOf("Enforces Law 1 (Research Before Executing) of the 7 Laws."), "1");
    });
    it("lifts a combined Law tag", () => {
        assert.equal(lawOf("Enforces Law 3 + 4 of the 7 Laws."), "3 + 4");
    });
    it("recognizes the all-7 and activator forms", () => {
        assert.equal(lawOf("Enforces all 7 Laws as a standing stance."), "all 7");
        assert.equal(lawOf("Law activator — routes tasks."), "activator");
    });
    it("returns undefined when no Law tag is present", () => {
        assert.equal(lawOf("Just a description."), undefined);
        assert.equal(lawOf(undefined), undefined);
    });
});
describe("skill-catalog — enforcementOf", () => {
    it("reports hook when the skill has a mapped hook", () => {
        const r = enforcementOf("gateguard", new Set());
        assert.equal(r.enforcement, "hook");
        assert.equal(r.hookFile, "gateguard.mjs");
    });
    it("prefers the hook over a same-named command", () => {
        assert.equal(enforcementOf("gateguard", new Set(["gateguard"])).enforcement, "hook");
    });
    it("reports command when only a slash command exists", () => {
        const r = enforcementOf("audit", new Set(["audit"]));
        assert.equal(r.enforcement, "command");
        assert.equal(r.hookFile, undefined);
    });
    it("fails closed to prose for an unmapped, uncommanded skill", () => {
        assert.equal(enforcementOf("some-future-skill", new Set()).enforcement, "prose");
    });
    it("never invents a hook for a skill missing from HOOK_BY_SKILL", () => {
        assert.equal(HOOK_BY_SKILL["some-future-skill"], undefined);
        assert.notEqual(enforcementOf("some-future-skill", new Set(["some-future-skill"])).enforcement, "hook");
    });
    it("maps every HOOK_BY_SKILL entry to a hook file that actually ships", () => {
        for (const [skill, file] of Object.entries(HOOK_BY_SKILL)) {
            const path = join(REPO_ROOT, "hooks", file);
            assert.doesNotThrow(() => readFileSync(path), `HOOK_BY_SKILL["${skill}"] points at hooks/${file}, which does not exist`);
        }
    });
});
describe("skill-catalog — summarize", () => {
    it("strips the Law preamble", () => {
        assert.equal(summarize("Enforces Law 1 (Research Before Executing) of the 7 Laws of AI Agent Discipline. Blocks edits."), "Blocks edits.");
    });
    it("leaves an untagged description alone", () => {
        assert.equal(summarize("Blocks edits."), "Blocks edits.");
    });
    it("returns empty string for a missing description", () => {
        assert.equal(summarize(undefined), "");
    });
});
describe("skill-catalog — renderSkillCatalogHtml", () => {
    const fixture = [
        { name: "continuous-improvement", tier: "core", description: "The 7 Laws.", enforcement: "prose" },
        {
            name: "gateguard",
            tier: "1",
            description: "Enforces Law 1 of the 7 Laws. Fact gate.",
            enforcement: "hook",
            hookFile: "gateguard.mjs",
            law: "1",
        },
        { name: "audit", tier: "2", description: "Enforces Law 4. Audits commits.", enforcement: "command", law: "4" },
    ];
    it("renders a complete standalone document", () => {
        const out = renderSkillCatalogHtml(fixture);
        assert.match(out, /^<!doctype html>/);
        assert.match(out, /<\/html>\n$/);
        assert.match(out, /<meta name="viewport"/);
    });
    it("carries the generated-file banner so nobody hand-edits it", () => {
        assert.match(renderSkillCatalogHtml(fixture), /GENERATED by npm run build/);
    });
    it("renders one badge per skill with the hook file named", () => {
        const out = renderSkillCatalogHtml(fixture);
        assert.match(out, /<span class="badge hook"[^>]*>hook<\/span>/);
        assert.match(out, /<span class="hookfile">hooks\/gateguard\.mjs<\/span>/);
        assert.match(out, /<span class="badge command"[^>]*>command<\/span>/);
        assert.match(out, /<span class="badge prose"[^>]*>prose<\/span>/);
    });
    it("counts each enforcement class in the summary line", () => {
        assert.match(renderSkillCatalogHtml(fixture), /1 are enforced by a hook, 1 by a slash command, and 1 by model-side/);
    });
    it("groups by tier and omits tiers with no skills", () => {
        const out = renderSkillCatalogHtml(fixture);
        assert.match(out, /<h2>Core \(1\)<\/h2>/);
        assert.match(out, /<h2>Tier 1 — beginner \(1\)<\/h2>/);
        assert.ok(!out.includes("Always bundled"), "companion section should be absent when no companions");
    });
    it("escapes HTML in skill descriptions", () => {
        const out = renderSkillCatalogHtml([
            { name: "x", tier: "2", description: "Uses <script> & \"quotes\".", enforcement: "prose" },
        ]);
        assert.ok(out.includes("&lt;script&gt; &amp; &quot;quotes&quot;"));
        assert.ok(!out.includes("<script>"), "raw script tag must not survive escaping");
    });
    it("renders an em dash when a skill carries no Law tag", () => {
        const out = renderSkillCatalogHtml([{ name: "x", tier: "2", enforcement: "prose" }]);
        assert.match(out, /<td class="law">—<\/td>/);
    });
});
describe("skill-catalog — generated docs/skill-catalog.html", () => {
    const html = readFileSync(join(REPO_ROOT, "docs", "skill-catalog.html"), "utf8");
    it("is in sync with the renderer's document shape", () => {
        assert.match(html, /^<!doctype html>/);
        assert.match(html, /GENERATED by npm run build/);
    });
    it("marks gateguard as hook-enforced", () => {
        assert.match(html, /gateguard<\/td><td class="law">1<\/td><td><span class="badge hook"/);
    });
});
